### ISSUE TITLE
载入模型出错

### ISSUE THREAD

**Issue by umiiwa** [JosephineRabbit/MLMSNet#4]
请问我的问题该如何解决呢？
自己的电脑没有gpu，想用cpu先测试一下。先去掉了代码里的.cuda()，然后将模型载入到cpu上，但是报了如下错误：

> RuntimeError: Error(s) in loading state_dict for DSS:
>Missing key(s) in state_dict: "base.0.weight", "base.0.bias", "base.2.weight", "base.2.bias", "base.5.weight", "base.5.bias", "base.7.weight", "base.7.bias", "base.10.weight", "base.10.bias", "base.12.weight", "base.12.bias", "base.14.weight", "base.14.bias", "base.17.weight", "base.17.bias", "base.19.weight", "base.19.bias", "base.21.weight", "base.21.bias", "base.24.weight", "base.24.bias", "base.26.weight", "base.26.bias", "base.28.weight", "base.28.bias", "feat.0.main.0.weight", "feat.0.main.0.bias", "feat.0.main.2.weight", "feat.0.main.2.bias", "feat.0.o.weight", "feat.0.o.bias", "feat.0.o2.weight", "feat.0.o2.bias", "feat.1.main.0.weight", "feat.1.main.0.bias", "feat.1.main.2.weight", "feat.1.main.2.bias", "feat.1.o.weight", "feat.1.o.bias", "feat.1.o2.weight", "feat.1.o2.bias", "feat.2.main.0.weight", "feat.2.main.0.bias", "feat.2.main.2.weight", "feat.2.main.2.bias", "feat.2.o.weight", "feat.2.o.bias", "feat.2.o2.weight", "feat.2.o2.bias", "feat.3.main.0.weight", "feat.3.main.0.bias", "feat.3.main.2.weight", "feat.3.main.2.bias", "feat.3.o.weight", "feat.3.o.bias", "feat.3.o2.weight", "feat.3.o2.bias", "feat.4.main.0.weight", "feat.4.main.0.bias", "feat.4.main.2.weight", "feat.4.main.2.bias", "feat.4.o.weight", "feat.4.o.bias", "feat.4.o2.weight", "feat.4.o2.bias", "feat.5.main.0.weight", "feat.5.main.0.bias", "feat.5.main.2.weight", "feat.5.main.2.bias", "feat.5.o.weight", "feat.5.o.bias", "feat.5.o2.weight", "feat.5.o2.bias", "up.0.weight", "up.0.bias", "up.1.weight", "up.1.bias", "up.2.weight", "up.2.bias", "up.3.weight", "up.3.bias", "up.4.weight", "up.4.bias", "up.5.weight", "up.5.bias", "up2.0.weight", "up2.0.bias", "up2.1.weight", "up2.1.bias", "up2.2.weight", "up2.2.bias", "up2.3.weight", "up2.3.bias", "up2.4.weight", "up2.4.bias", "up2.5.weight", "up2.5.bias". 
> Unexpected key(s) in state_dict: "module.base.0.weight", "module.base.0.bias", "module.base.2.weight", "module.base.2.bias", "module.base.5.weight", "module.base.5.bias", "module.base.7.weight", "module.base.7.bias", "module.base.10.weight", "module.base.10.bias", "module.base.12.weight", "module.base.12.bias", "module.base.14.weight", "module.base.14.bias", "module.base.17.weight", "module.base.17.bias", "module.base.19.weight", "module.base.19.bias", "module.base.21.weight", "module.base.21.bias", "module.base.24.weight", "module.base.24.bias", "module.base.26.weight", "module.base.26.bias", "module.base.28.weight", "module.base.28.bias", "module.feat.0.main.0.weight", "module.feat.0.main.0.bias", "module.feat.0.ed1.0.weight", "module.feat.0.ed1.0.bias", "module.feat.0.ed2.0.weight", "module.feat.0.ed2.0.bias", "module.feat.0.main3.0.weight", "module.feat.0.main3.0.bias", "module.feat.0.o.weight", "module.feat.0.o.bias", "module.feat.0.o2.weight", "module.feat.0.o2.bias", "module.feat.1.main.0.weight", "module.feat.1.main.0.bias", "module.feat.1.main.2.weight", "module.feat.1.main.2.bias", "module.feat.1.o.weight", "module.feat.1.o.bias", "module.feat.1.o2.weight", "module.feat.1.o2.bias", "module.feat.2.main.0.weight", "module.feat.2.main.0.bias", "module.feat.2.ed1.0.weight", "module.feat.2.ed1.0.bias", "module.feat.2.ed2.0.weight", "module.feat.2.ed2.0.bias", "module.feat.2.main3.0.weight", "module.feat.2.main3.0.bias", "module.feat.2.o.weight", "module.feat.2.o.bias", "module.feat.2.o2.weight", "module.feat.2.o2.bias", "module.feat.3.main.0.weight", "module.feat.3.main.0.bias", "module.feat.3.main.2.weight", "module.feat.3.main.2.bias", "module.feat.3.o.weight", "module.feat.3.o.bias", "module.feat.3.o2.weight", "module.feat.3.o2.bias", "module.feat.4.main.0.weight", "module.feat.4.main.0.bias", "module.feat.4.ed1.0.weight", "module.feat.4.ed1.0.bias", "module.feat.4.ed2.0.weight", "module.feat.4.ed2.0.bias", "module.feat.4.main3.0.weight", "module.feat.4.main3.0.bias", "module.feat.4.o.weight", "module.feat.4.o.bias", "module.feat.4.o2.weight", "module.feat.4.o2.bias", "module.feat.5.main.0.weight", "module.feat.5.main.0.bias", "module.feat.5.main.2.weight", "module.feat.5.main.2.bias", "module.feat.5.o.weight", "module.feat.5.o.bias", "module.feat.5.o2.weight", "module.feat.5.o2.bias", "module.e_feat.0.conv1.0.weight", "module.e_feat.0.conv1.0.bias", "module.e_feat.0.conv2.0.weight", "module.e_feat.0.conv2.0.bias", "module.e_feat.0.conv2.2.weight", "module.e_feat.0.conv2.2.bias", "module.e_feat.0.merge.weight", "module.e_feat.0.merge.bias", "module.e_feat.1.conv1.0.weight", "module.e_feat.1.conv1.0.bias", "module.e_feat.1.conv2.0.weight", "module.e_feat.1.conv2.0.bias", "module.e_feat.1.conv2.2.weight", "module.e_feat.1.conv2.2.bias", "module.e_feat.1.merge.weight", "module.e_feat.1.merge.bias", "module.e_feat.2.conv1.0.weight", "module.e_feat.2.conv1.0.bias", "module.e_feat.2.conv2.0.weight", "module.e_feat.2.conv2.0.bias", "module.e_feat.2.conv3.0.weight", "module.e_feat.2.conv3.0.bias", "module.e_feat.2.conv3.2.weight", "module.e_feat.2.conv3.2.bias", "module.e_feat.2.merge.weight", "module.e_feat.2.merge.bias", "module.e_feat.3.conv1.0.weight", "module.e_feat.3.conv1.0.bias", "module.e_feat.3.conv2.0.weight", "module.e_feat.3.conv2.0.bias", "module.e_feat.3.conv3.0.weight", "module.e_feat.3.conv3.0.bias", "module.e_feat.3.conv3.2.weight", "module.e_feat.3.conv3.2.bias", "module.e_feat.3.merge.weight", "module.e_feat.3.merge.bias", "module.e_feat.4.conv1.0.weight", "module.e_feat.4.conv1.0.bias", "module.e_feat.4.conv2.0.weight", "module.e_feat.4.conv2.0.bias", "module.e_feat.4.conv3.0.weight", "module.e_feat.4.conv3.0.bias", "module.e_feat.4.conv3.2.weight", "module.e_feat.4.conv3.2.bias", "module.e_feat.4.merge.weight", "module.e_feat.4.merge.bias", "module.up_e.0.weight", "module.up_e.0.bias", "module.up_e.1.weight", "module.up_e.1.bias", "module.up_e.2.weight", "module.up_e.2.bias", "module.up_e.3.weight", "module.up_e.3.bias", "module.up_e.4.weight", "module.up_e.4.bias", "module.up_sal.0.weight", "module.up_sal.0.bias", "module.up_sal.1.weight", "module.up_sal.1.bias", "module.up_sal.2.weight", "module.up_sal.2.bias", "module.up_sal.3.weight", "module.up_sal.3.bias", "module.up_sal.4.weight", "module.up_sal.4.bias", "module.up_sal.5.weight", "module.up_sal.5.bias", "module.up_sal.6.weight", "module.up_sal.6.bias", "module.up_sal_e.0.weight", "module.up_sal_e.0.bias", "module.up_sal_e.1.weight", "module.up_sal_e.1.bias", "module.up_sal_e.2.weight", "module.up_sal_e.2.bias", "module.up_sal_e.3.weight", "module.up_sal_e.3.bias", "module.up_sal_e.4.weight", "module.up_sal_e.4.bias", "module.up_sal_e.5.weight", "module.up_sal_e.5.bias", "module.up_sal_e.6.weight", "module.up_sal_e.6.bias", "module.fuse_e.weight", "module.fuse_e.bias". 

参考网上的建议，我在载入的时候先去掉了名称中的‘module’，例如：

```
state_dict = torch.load('./checkpoints/decoder.pkl', map_location='cpu')
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:] 
    new_state_dict[name] = v
U.load_state_dict(new_state_dict)
```

但是依然报错：

> Missing key(s) in state_dict: "feat.0.main.2.weight", "feat.0.main.2.bias", "feat.2.main.2.weight", "feat.2.main.2.bias", "feat.4.main.2.weight", "feat.4.main.2.bias", "up.0.weight", "up.0.bias", "up.1.weight", "up.1.bias", "up.2.weight", "up.2.bias", "up.3.weight", "up.3.bias", "up.4.weight", "up.4.bias", "up.5.weight", "up.5.bias", "up2.0.weight", "up2.0.bias", "up2.1.weight", "up2.1.bias", "up2.2.weight", "up2.2.bias", "up2.3.weight", "up2.3.bias", "up2.4.weight", "up2.4.bias", "up2.5.weight", "up2.5.bias". 
> Unexpected key(s) in state_dict: "e_feat.0.conv1.0.weight", "e_feat.0.conv1.0.bias", "e_feat.0.conv2.0.weight", "e_feat.0.conv2.0.bias", "e_feat.0.conv2.2.weight", "e_feat.0.conv2.2.bias", "e_feat.0.merge.weight", "e_feat.0.merge.bias", "e_feat.1.conv1.0.weight", "e_feat.1.conv1.0.bias", "e_feat.1.conv2.0.weight", "e_feat.1.conv2.0.bias", "e_feat.1.conv2.2.weight", "e_feat.1.conv2.2.bias", "e_feat.1.merge.weight", "e_feat.1.merge.bias", "e_feat.2.conv1.0.weight", "e_feat.2.conv1.0.bias", "e_feat.2.conv2.0.weight", "e_feat.2.conv2.0.bias", "e_feat.2.conv3.0.weight", "e_feat.2.conv3.0.bias", "e_feat.2.conv3.2.weight", "e_feat.2.conv3.2.bias", "e_feat.2.merge.weight", "e_feat.2.merge.bias", "e_feat.3.conv1.0.weight", "e_feat.3.conv1.0.bias", "e_feat.3.conv2.0.weight", "e_feat.3.conv2.0.bias", "e_feat.3.conv3.0.weight", "e_feat.3.conv3.0.bias", "e_feat.3.conv3.2.weight", "e_feat.3.conv3.2.bias", "e_feat.3.merge.weight", "e_feat.3.merge.bias", "e_feat.4.conv1.0.weight", "e_feat.4.conv1.0.bias", "e_feat.4.conv2.0.weight", "e_feat.4.conv2.0.bias", "e_feat.4.conv3.0.weight", "e_feat.4.conv3.0.bias", "e_feat.4.conv3.2.weight", "e_feat.4.conv3.2.bias", "e_feat.4.merge.weight", "e_feat.4.merge.bias", "up_e.0.weight", "up_e.0.bias", "up_e.1.weight", "up_e.1.bias", "up_e.2.weight", "up_e.2.bias", "up_e.3.weight", "up_e.3.bias", "up_e.4.weight", "up_e.4.bias", "up_sal.0.weight", "up_sal.0.bias", "up_sal.1.weight", "up_sal.1.bias", "up_sal.2.weight", "up_sal.2.bias", "up_sal.3.weight", "up_sal.3.bias", "up_sal.4.weight", "up_sal.4.bias", "up_sal.5.weight", "up_sal.5.bias", "up_sal.6.weight", "up_sal.6.bias", "up_sal_e.0.weight", "up_sal_e.0.bias", "up_sal_e.1.weight", "up_sal_e.1.bias", "up_sal_e.2.weight", "up_sal_e.2.bias", "up_sal_e.3.weight", "up_sal_e.3.bias", "up_sal_e.4.weight", "up_sal_e.4.bias", "up_sal_e.5.weight", "up_sal_e.5.bias", "up_sal_e.6.weight", "up_sal_e.6.bias", "fuse_e.weight", "fuse_e.bias", "feat.0.ed1.0.weight", "feat.0.ed1.0.bias", "feat.0.ed2.0.weight", "feat.0.ed2.0.bias", "feat.0.main3.0.weight", "feat.0.main3.0.bias", "feat.2.ed1.0.weight", "feat.2.ed1.0.bias", "feat.2.ed2.0.weight", "feat.2.ed2.0.bias", "feat.2.main3.0.weight", "feat.2.main3.0.bias", "feat.4.ed1.0.weight", "feat.4.ed1.0.bias", "feat.4.ed2.0.weight", "feat.4.ed2.0.bias", "feat.4.main3.0.weight", "feat.4.main3.0.bias".

**Comment by JosephineRabbit** [comment]
你好，模型在保存的时候已经去掉了其他两个分支，直接按test里载入model.py即可。
