### ISSUE TITLE
请问你们测试MAE指标的代码可以公开么？发现数据与我测试的对不上

### ISSUE THREAD

**Issue by thb1314** [JosephineRabbit/MLMSNet#5]
RT，我在实践中想测试一下您提供的图片与GT的一些指标，顺带着测了MAE，发现对不上

**Comment by JosephineRabbit** [comment]
pr曲线代码放在项目里了

**Comment by chiukin** [comment]
我测了一下，差异有点大

**Comment by JosephineRabbit** [comment]
是吗？我重新测试了一次SOD低了一点，omron 上fmeasure高了一点mae低了一点，其他基本一样啊。

**Comment by chiukin** [comment]
https://github.com/ArcherFMY/sal_eval_toolbox，我是用这个测试的，可能也是你们团队的学生写的。用你的结果图直接测，跟你论文上的不一样

**Comment by JosephineRabbit** [comment]
你试试我工程里的pr_curve呢？我稍后用matlab用上面的代码测一下。我刚刚好像找到去年8月的结果了稍等我再传一次。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chiukin"<notifications@github.com&gt;; 
发送时间: 2019年10月18日(星期五) 晚上6:04
收件人: "JosephineRabbit/MLMSNet"<MLMSNet@noreply.github.com&gt;; 
抄送: "吴润民"<429774648@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [JosephineRabbit/MLMSNet] 请问你们测试MAE指标的代码可以公开么？发现数据与我测试的对不上 (#5)




https://github.com/ArcherFMY/sal_eval_toolbox，我是用这个测试的，可能也是你们团队的学生写的。用你的结果图直接测，跟你论文上的不一样
